version: '3.8'
services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - "APP_ENV=dev"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: symfony_db
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: summarySeries
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: